### ISSUE TITLE
ＤＢ構造は、見直す予定です

### ISSUE THREAD

**Issue by u-10bei** [OCH-zoomPJ/zoomurl#1]
・ホストキーを管理するテーブルの作成
・プライマリーキーの設定
・検索用ビューの作成検討

**Comment by kawhi6key** [comment]
Google Calendar から取得できる情報で、DBに格納する情報はどの情報が適切でしょうか？
Calendar API Resource representations -> https://developers.google.com/calendar/api/v3/reference/events#resource
プライマリーキーですが、Calendar Event の "id" としても問題ないでしょうか？

**Comment by u-10bei** [comment]
今週末をめどにＥＲ図を公開する予定ですが、現行のzoom_urlテーブルに格納していただき、プライマリーキーはおっしゃるとおり、Eventsのidになるはずです。
meetingId以降が、google calendarを基に予約したzoomの情報となると考えています。

**Comment by u-10bei** [comment]
> 今週末をめどにＥＲ図を公開する予定ですが、現行のzoom_urlテーブルに格納していただき、プライマリーキーはおっしゃるとおり、Eventsのidになるはずです。 meetingId以降が、google calendarを基に予約したzoomの情報となると考えています。

と書きましたが、昨夜のミーティングを終えて仕様が変わりましたので、とりあえず報告します。
